uc-cdis/indexd

tests/test_setup.py
Adds check for older versions of SQLite3 before performing testing. Specifically, before v3.7.16 the documentation surrounding the primary key column for the table_info pragma was not in place. This resulted in the pk column always being listed as 1 for columns that were part of the primary key. In later versions, it was specified that the pk column should list base-1 position of the column in regards to use in the primary key.
=> check sqlite3 version for pk column convention

indexd/blueprint.py, indexd/errors.py, tests/test_blueprint.py
Adds custom configuration errors to blueprint. This ensures that any configuration error can be caught by catching the ```ConfigurationError``` exception type.
=> adds config errors

bin/indexd, indexd/alias/blueprint.py, indexd/auth/__init__.py, indexd/auth/driver.py, indexd/auth/drivers/alchemy.py, indexd/auth/errors.py, indexd/blueprint.py, indexd/errors.py, indexd/index/blueprint.py, setup.py, tests/test_driver_alchemy_auth.py
This adds basic auth to all data-modifying endpoints. This is done by implementing `indexd.auth.driver.AuthDriverABC` abstract base class, similar to the index and alias drivers, and registering functions as requiring auth via the `indexd.auth.authorize` decorator. Requests routed to handlers wrapped in the `authorize` decorator will be authenticated using the username and password in `flask.request.authorization`. If authenticated, the `flask.request.authorization` property will be replaced with a user context dictionary that provides user privilege information, such as username and roles.
Currently there is no way to create, modify or delete credentials. Credentials must be handled directly in the auth backend database. This should be handled via a separate pull request to add `/auth` …
=> adds basic auth

indexd/index/blueprint.py
handle request payload's json elements same way as in [alias](https://github.com/LabAdvComp/indexd/blob/develop/indexd/alias/blueprint.py#L110) blueprint, avoiding 500 caused by `KeyError`
r? @MurphyMarkW
=> fix(request-json): use dict.get

indexd/index/drivers/alchemy.py
the previous join only joined on index_record and index_record_hash table, actually didn't filter out index_record_url by hashes
previous query:
```
print index_s.query(IndexRecordUrl).join(IndexRecord.hashes).filter(and_(Inde
xRecordHash.hash_value=='f787197cffb8ee0e9e4f061b89b61a07'))
SELECT index_record_url.did AS index_record_url_did, index_record_url.url AS index_record_url_url 
FROM index_record_url, index_record JOIN index_record_hash ON index_record.did = index_record_hash.did 
WHERE index_record_hash.hash_value = %(hash_value_1)s
```
current query:
```
print index_s.query(IndexRecordUrl).join(IndexRecordUrl.index_record).join(In
dexRecord.hashes).filter(and_(IndexRecordHash.hash_value=='f787197cffb8ee0e9e4f061b89b
61a07'))
SELECT index_record_url.did AS index_record_url_did, …
```
=> fix(url-query): fix join query

bin/index_admin.py, indexd/alias/drivers/alchemy.py, indexd/default_settings.py, indexd/index/drivers/alchemy.py, indexd/utils.py, tests/test_schema_migration.py, tests/test_setup.py
- still keep alias and index separate as is
- initialize any db with version 0
- auto migrate to latest version based on version diff
when we need a version upgrade, the pr will bump the version in `SQLAlchemyIndexDriver.current_version`, and create a migration function appended to [all_migration_functions](https://github.com/uc-cdis/indexd/compare/feat/schema_version?expand=1#diff-395f548de47be5f9dbaf677448d33ff1R102)
=> feat(schema_version): track schema and migrate

indexd/alias/drivers/alchemy.py, indexd/index/drivers/alchemy.py
Fix couple of issues:
- make create_all() for both old empty and old non-empty DB
- in case of brand-new db, don't need run migrate scripts
=> fix(migration): fix migration scripts

indexd/index/drivers/alchemy.py, tests/test_client.py
Adding base_version to the database violated the unique constraint on the
baseid column of that table. But since a user can provide a baseid as
part of the create step, this constraint isn't as important outside of
baseid being the primary key of base_version. So it is safe to merge.
=> fix(merge): merge base_version instead of add

indexd/index/blueprint.py, indexd/index/driver.py, indexd/index/drivers/alchemy.py, indexd/index/schema.py, tests/test_client.py, tests/test_driver_alchemy_crud.py
```
if version is not None:
record.version = version
```
This behavior blocks being able to nullify the version field. This PR gets rid of this by simply setting it to whatever is coming from the request. Looking at 
https://github.com/uc-cdis/indexd/blob/415f7338845f3e3aa6398d368d85157caab97b50/indexd/index/blueprint.py#L275
there is a possibility that this field is intentionally not set (which resolves to None either way), hence removing the check above leads to unintended results. Which led me to a second solution which uses a sentinel (eg -1, @, ^ etc); which will imply that the user needs to know this special symbol not to use in their versioning scheme. I skipped this solution cos of that.
The implemented solution is in line with using the IndexClient, since to do an update you will …
=> fix(update_doc): allow setting version to None 

indexd/bulk/blueprint.py, indexd/default_settings.py
Temporarily enabled SQLAlchemy logging in default_settings.py to log the actual SQL queries.
=> fix(bulk-eager): use joinedload for query in bulk API.

README.md, indexd/index/blueprint.py, indexd/index/drivers/alchemy.py, indexd/index/errors.py, openapis/swagger.yaml, tests/test_client.py
New endpoint for blank records containing just the `uploader` field
- Allow creating empty records
- Query by empty acl
- Support filling (still not modifying) hash
=> PXD-2213 Feat/empty record

indexd/index/drivers/alchemy.py
Eliminate the possibility of duplicate ACLs in the ACL list.
The database table `index_record_ace`'s primary key is (did, acl), so we shouldn't allow duplicates in the ACL list when making an IndexRecord. Using a set removes the duplicates.
=> fix(api-568): eliminate duplicate ACLs

README.md, indexd/index/blueprint.py, indexd/index/drivers/alchemy.py, openapis/swagger.yaml, tests/test_client.py, tests/util.py
When users go see all the uploaded files in windmill, they should be able to see the file names.
- Update the blank record creation endpoint in indexd to support providing the file name.
- indexd records created during the data upload flow will contain the file names.
=> PXD-2415 Feat/file name

TestDockerfile
Docker tests now run and all pass (except for `test_migrate_index_versioning`, which is noted in the README).
None
None
* Fix Docker testing harness failing on start because `gnupg2` is not installed.
None
* `gnupg2` is now installed when running tests with Docker
None
=> Install gnupg2 for Docker tests (closes #187)

indexd/dos/blueprint.py, openapis/swagger.yaml, tests/test_client.py
This PR updates the behavior of DRS endpoints such that it reflects the changes and features introduced in v0.5.0 (from v0.2.0). The commit message has a few more details.
* DRS v0.5.0 compliance
* Functionality of `POST /dataobjects/list` has been moved to `GET /dataobjects`, and the parameters provided to this endpoint are now specified as query parameters instead of in the request body.
None
* Specification of required and optional parameters has been properly serialized in the schema.
* `checksum` parameter is now optional for ListDataBundles and ListDataObjects.
* Minor changes for PEP8 compliance.
None
None
cc @david4096
=> Implement DRS v0.5.0 (closes #146)

.travis.yml, TestDockerfile, requirements.txt
tldr: bump sqlalchemy and sqlalchemy-utils. Also specify jdk 8 in .travis.yml. 
------------------------
Tried to just bump sqlalchemy and sqlalchemy-utils. Travis error:
```
Package oracle-java8-set-default is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
oracle-java9-set-default
```
Probably because: https://launchpad.net/~webupd8team/+archive/ubuntu/java 
The Travis dist was `trusty` (just because that is the default)(...[until tomorrow!](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment)). Switching from java8 to java9 worked, as did doing 
```
before_install:
- jdk_switcher use oraclejdk8
``` 
in trusty. But we …
=> bump sqlalchemy and sqlalchemy-utils; update .travis.yml

bin/migrate_acl_authz.py
- Add script to run for filling out records' `authz` fields based on the `acl` fields.
=> chore(authz-migration): add migration script

.coveragerc, .gitignore, .travis.yml, README.md, openapis/swagger.yaml
Remove swagger-codegen installation from travis setup and readme
Exclude abstract methods from coverage report
Improve descriptions in swagger doc
- Exclude abstract methods from coverage report
=> chore(coverage)

indexd/index/blueprint.py, tests/test_client.py
Add unit tests to improve test coverage.
- Adds unit tests.
=> tests(misc): add unit tests

bin/migrate_acl_authz.py, indexd/bulk/blueprint.py, requirements.txt, setup.py, tests/test_driver_alchemy_auth.py, tests/test_driver_alchemy_crud.py, tests/test_schema_migration.py
Dependency updates
- Flask 1.1.1
=> chore(flask-vulnerability): bump flask to 1.1.1

Dockerfile
- Use python 3 base dockerfile v1.1.0 to disable uwsgi cheaper mode
=> python 3 base v1.1.0

indexd/alias/drivers/alchemy.py, indexd/index/blueprint.py, indexd/index/drivers/alchemy.py, openapis/swagger.yaml, tests/test_client.py
- add `page` param to list records endpoint to support pagination without using a did
=> feat(page): add page param to support pagination without knowing dids

bin/migrate_acl_authz.py
- Add option to enable/disable the use of arborist tags in ACL->authz migration script (disabled by default)
- Fix bug in ACL->authz migration script that removed non-word characters from ACL elements
=> fix(migrate)

indexd/index/drivers/alchemy.py, setup.py, tests/test_client.py
because of the unpinned authutils, version “5.0.0b1" was being installed, which tried to install cdiserrors version "1.0.0b1" and errored
- Prepend the configured prefix to new versions' GUIDs, unless a GUID has been provided by the user
- Pin authutils==4.0.0 in setup.py
=> Prepend prefix to new versions

indexd/auth/drivers/alchemy.py, requirements.txt, setup.py
fix error:
```
File "/usr/local/lib/python3.6/site-packages/rbac/client/arborist/client.py", line 152, in auth_request
msg = "request to arborist failed: {}".format(response.json())
TypeError: 'dict' object is not callable
```
- update gen3authz to latest version
=> gen3rbac==0.1.2 -> gen3authz==0.4.0

indexd/index/blueprint.py, indexd/index/drivers/alchemy.py, openapis/swagger.yaml, tests/test_client.py
Jira Ticket: [PXP-5525](https://ctds-planx.atlassian.net/browse/PXP-5525)
Adds support for the POST `/index/blank/{{GUID}}` endpoint, which allows creation of a new blank version of an existing record.
- Add support for creating a new, blank version of a record through the POST `/index/blank/{{GUID}}` endpoint.
=> (PXP-5525): Add blank version of record

Jenkinsfile, indexd/index/blueprint.py, indexd/index/drivers/alchemy.py, indexd/index/schema.py, openapis/swagger.yaml, test-requirements.txt, tests/conftest.py, tests/test_client.py
Jira Ticket: [PXP-1745](https://ctds-planx.atlassian.net/browse/PXP-1745)
Adds a new endpoint to indexd, PUT `/index/{GUID}/versions`, allowing user to update the `acl` and `authz` fields across all versions of a record.
- Added PUT `/index/{GUID}/versions` endpoint, allowing user to update the `acl` and `authz` fields across all versions of a record.
=> (PXP-1745): Update acl/authz across all versions

indexd/auth/__init__.py, indexd/index/blueprint.py, indexd/index/drivers/alchemy.py, openapis/swagger.yaml, test-requirements.txt, tests/conftest.py, tests/test_client.py, tests/util.py
Jira Ticket: [PXP-6156](https://ctds-planx.atlassian.net/browse/PXP-6156)
closes #278
- `authz` for blank endpoints
- Fix bug when `authorize()` is called more than once
- Fix bug in `update_all_versions` authz check
- Pin `swagger_spec_validator` to 2.6.0 because version 2.7.0 fails with:
```
def test_valid_openapi():
[...]
>       validator.validate_spec(spec, url)
def validate_definition(definition, deref, def_name=None, visited_definitions_ids=None):
[...]
>       swagger_type = definition.get('type')
E       AttributeError: 'bool' object has no attribute 'get'
```
- "POST /blank", "POST /blank/GUID" and "PUT /blank/GUID" endpoints now allow specifying an authz for the blank record
- "PUT /index/GUID" (record update) now checks authorization for both update (old authz) and create (new …
=> PXP-6156 "authz" for blank endpoints

bin/migrate_acl_authz.py, requirements.txt, setup.py
Fix migration script:
- For ACL `['PROG', 'PROJ']` we get path = `/programs/PROG/projects/PROJ`
- For ACL `['PROJ', 'PROG']` we get `EnvironmentError: program or project PROG does not exist`
The script will also now raise an error for ACL `[<project that exists>, <program that doesn't exist>]` instead of just using the project to generate the path
Also, `sqlalchemy-utils 0.36.8` is breaking indexd: `FATAL:  database "indexd_user" does not exist`
so limiting to working versions `sqlalchemy-utils>=0.33.11,<=0.36.6`
see https://github.com/kvesteri/sqlalchemy-utils/issues/462
- Fix ACL->authz migration script for "[ project, program ]" ACLs
- Add sqlalchemy-utils upper bound "<=0.36.6" in addition to ">=0.33.11"
=> Fix ACL->authz migration script for "[ project, program ]" ACLs

indexd/index/blueprint.py, indexd/index/drivers/alchemy.py, tests/test_aliases_endpoints.py, tests/test_client.py, tests/test_driver_alchemy_crud.py
- Fix 500 error when indexd blank endpoints are called without a body: `AttributeError: 'NoneType' object has no attribute 'get'`
- Return 400 instead of 409 in case of conflict (records / aliases): `MultipleRecordsFound` instead of `UserError`
- Fix 500 error when indexd blank endpoints are called without a body
- Return 400 instead of 409 in case of conflict
=> Return 409 in case of conflict

README.md, indexd/blueprint.py, indexd/drs/blueprint.py, indexd/index/blueprint.py, indexd/index/drivers/alchemy.py, tests/test_driver_alchemy_crud.py
Jira Ticket: [PXP-6604](https://ctds-planx.atlassian.net/browse/PXP-6604)
Now when attempting to GET a record for a specified GUID, the following resolution steps will be taken:
1. Start by trying to resolve the provided ID
2. If unsuccessful, check what the `DEFAULT_PREFIX` Indexd config is set to
3. If the ID starts with the prefix, attempt to remove the prefix from the provided ID and try resolving again
4. If the ID does not start with the prefix, attempt to add the prefix to the provided ID and try resolving again
- Added new `get_with_nonstrict_prefix` helper to `index_driver`.
- Updated `/ga4gh/drs/v1/objects/<path:object_id>` and `/index/<path:object_id>` GET endpoints to utilize this new method.
=> (PXP-6604) DRS endpoint to resolve regardless of prefix

indexd/index/drivers/alchemy.py
- update updated_date when modifying record
=> fix(updated): actually update updated_date when modifying record

.secrets.baseline, indexd/index/drivers/alchemy.py, tests/test_client.py
Jira Ticket: [PXP-7008](https://ctds-planx.atlassian.net/browse/PXP-7008)
Fix overwriting of `acl` and `authz` fields to `[]` on `POST` to `/index/blank/{guid}`.
- fix overwriting of `acl` and `authz` fields to `[]` on `POST` to `/index/blank/{guid}`
=> (PXP-7008): fix overwriting of acl and authz fields to [] on POST to /index/blank/{guid}

Dockerfile
Unblocking release202101 by avoiding a timeout in our indexd Docker build, which is caused by the following operation in Quay:
```
12/16/2020, 5:07:10 PMINFO: pip is looking at multiple versions of psycopg2 to determine 
which version is compatible with other requirements. This could take a while.
12/16/2020, 5:07:10 PMCollecting psycopg2>=2.7 
```
- Use `--use-deprecated=legacy-resolver` to avoid issues with the latest pip (>=20.3).
=> chore(indexd): Utilize legacy-resolver to unblock indexd img builds

.secrets.baseline, indexd/fence_client.py, tests/test_drs.py
- all url query parameters sent to the DRS signed url endpoint now propagate to the corresponding Fence request (instead of stripping off all query params)
=> PXP-7557: Propagate params in DRS signed url endpoint 

indexd/auth/drivers/alchemy.py
`gen3authz.auth_request` returns True if authorized or False if unauthorized, but it can also return an Exception if the request to Arborist failed; the indexd_admin code did not handle the latter case
- Fix "indexd admin" logic to handle failed authorization requests to Arborist
=> Handle failed authz requests to Arborist

indexd/alias/drivers/alchemy.py, indexd/auth/drivers/alchemy.py, indexd/blueprint.py, indexd/index/blueprint.py, indexd/index/drivers/alchemy.py, tests/conftest.py
- Bundles endpoints: don't swallow authorization exceptions
- Add a deprecation log to the old "indexd_admin" logic
=> Bundles: don't swallow exception + Old indexd_admin deprecation log

Dockerfile, pyproject.toml
Suppressing UWSGI & NGINX metrics in favour of DataDog’s telemetry / python APM / probing -- hoping we can achieve the same observability with it.
Once we retire the k8s sidecar containers from indexd's k8s YAML (here: https://github.com/uc-cdis/cloud-automation/pull/1643), old indexd images will face a lot of log noise as the HTTP metrics endpoints will no longer exist.
=> chore(pybase3): Update pybase img de novo

bin/config_helper.py, bin/creds.json, bin/indexd_settings.py, deployment/Secrets/config_helper.py, deployment/Secrets/indexd_creds.json, deployment/Secrets/indexd_settings.py, deployment/scripts/indexd/indexd_setup.sh, deployment/scripts/postgresql/postgresql_init.sql, deployment/uwsgi/uwsgi.ini, tests/default_test_settings.py
* Add `indexd` settings files for PostgreSQL SSL support
* Clean up test settings
* Include example secrets to load PostgreSQL settings for `indexd`
=> Add files for psql ssl support

indexd/drs/blueprint.py, tests/test_drs.py
- Remove `contents` field from DRS Blob objects
=> PXP-9190: Remove Contents from DRS blobs

poetry.lock, pyproject.toml
- Upgrade PyYAML to version 5.4 or higher.
=> chore(deps): update pyyaml, relock

.secrets.baseline, .travis.yml, indexd/index/drivers/alchemy.py
indexd's GET endpoint checks if a record exists and if not, if a bundle exists. If neither exist, we currently return the error message "no bundle found" that comes from `get_bundle()`. We should return "no record found" instead since this endpoint is not specific to bundles
- Update `GET /index/<GUID>` error message
=> Update error message

indexd/drs/blueprint.py
Currently the DRS response version prefers indexd rev instead of version.
This prefers version before rev. If version is not available it should fallback to rev.
- DRS response prefers version before rev, if version is not available it uses rev
=> PXP-10714: Prefer version to rev

.gitignore, .secrets.baseline, indexd/drs/blueprint.py, indexd/index/blueprint.py, indexd/index/driver.py, indexd/index/drivers/alchemy.py, indexd/index/schema.py, migrations/versions/a72f117515c5_add_description_created_time_and_.py, openapis/swagger.yaml, tests/postgres/migrations/test_a72f117515c5_add_description_created_time_and_.py, tests/test_client.py, tests/test_driver_alchemy_crud.py, tests/test_drs.py, tests/test_setup.py
Jira Ticket: [DCF-450](https://ctds-planx.atlassian.net/browse/DCF-450)
- Adds description, content_updated_time and content_created_time to IndexRecord.
- DRS responses now map updated_time and created_time to the underlying content's updated and created times. 
- DRS responses now include index_created_time and index_updated_time to denote the time they were indexed and the time their index record was changed. These fields replace the previous updated_time and created_time in older indexd versions. 
- DRS responses for update_time and created_time reflect the content's updated and created times, not the time the were indexed or their index record was updated. 
- New columns added to index_record table. Alembic migration needed. 
[DCF-450]: …
=> feat(DCF-450): Add DRS Fields

.github/labeler.yml, .github/workflows/labeler.yml
Jira Ticket: [GQE-74](https://ctds-planx.atlassian.net/browse/GQE-74)
[GQE-74]: https://ctds-planx.atlassian.net/browse/GQE-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> adding labeler to run appro tests

pyproject.toml
=> Allow any python 3.9

indexd/index/blueprint.py, indexd/index/drivers/alchemy.py, pyproject.toml, tests/test_client.py, tests/test_drs.py
- Indexd records no longer return empty strings for content_updated_date and content_updated_time when not provided.
=> Change content date defaults to None from ''

Dockerfile, indexd/index/drivers/single_table_alchemy.py, poetry.lock, pyproject.toml
Link to JIRA ticket if there is one: 
- Fix resource authorize checks for delete and alias endpoints in single table alchemy
=> Fix delete endpoints in Single Table
