uc-cdis/indexd

- README.md
Updates the README with a draft overview of installation, configuration and records.
> updates README with rough draft overview

- indexd/alias/blueprint.py
- indexd/index/blueprint.py
- indexd/index/drivers/alchemy.py
> fixes various bugs

- indexd/index/drivers/alchemy.py
Fixes set intersection of hashes to form minimal matching set.
> fixes hash set intersections

- indexd/alias/drivers/alchemy.py
- indexd/index/drivers/alchemy.py
Was not properly sorting results in ascending order.
> fixes sorting order of aliases and dids

- .gitignore
- bin/indexd
- indexd/__init__.py
- indexd/app.py
- indexd/default_settings.py
- setup.py
- wsgi.py
may not be the best setup, suggestions? @MurphyMarkW
> feat(configs): setup app configuration

- indexd/alias/drivers/alchemy.py
- indexd/blueprint.py
- handle NoRecordFound in cross blueprint
- remove print statement
r? @MurphyMarkW
> fix(error-handling): handle 404 in cross bp

- Dockerfile
Apache need to pass through the auth headers to wsgi for create/update/delete actions.
r? @zflamig
> fix(auth): pass basic auth to wsgi app

- bin/index_admin.py
- indexd/auth/__init__.py
- indexd/auth/driver.py
- indexd/auth/drivers/alchemy.py
- indexd/default_settings.py
r? @zflamig 
jira ticket [BIS-1](https://jira.opensciencedatacloud.org/browse/BIS-1)
> feat(admin): add script to create and delete user

- Dockerfile
- README.md
- bin/index_admin.py
- fall back to default settings if no local_settings found
- add documentation
- fix default local_settings path
r? @zflamig
> fix/user-creation - fix default settings

- .travis.yml
- Dockerfile
- dockerrun.bash
- indexd/app.py
- setup.cfg
- setup.py
- add stdout handler
- calls wsgi.py onload to make sure everything is loaded and database is touched
This is a problem with docker's apache2 setup & default sqlite db file.
apache2 uses www-data as the default user for wsgi process, it then imports libraries on first request. So sqlite db files are created by www-data on first request.
But if you execute index_admin.py as another user before wsgi process, it will create db files under this user, making wsgi process unable to write to the sqlite file.
> Feat/logger - add stream handler

- .travis.yml
- indexd/app.py
- indexd/default_settings.py
- indexd/index/drivers/alchemy.py
- test-requirements.txt
- tests/conftest.py
- tests/test_client.py
- two sanity checks to flask test client
- pep8 formatting
- python3 compatibility, apparently our previous test coverage is not good enough to find all incompatible code
r? @zflamig
> test(client): add simple tests to client

- indexd/index/blueprint.py
- indexd/index/drivers/alchemy.py
- indexd/index/schema.py
resolve https://github.com/LabAdvComp/indexd/issues/39
r? @rudyardrichter
> feat(creat): support creation with specified did

- README.md
add swagger link
add some docs, mainly copied from gdc doc
> docs(readme): add swagger link

- README.md
> chore(org-move): move to uc-cdis

- README.md
- indexd/index/blueprint.py
- indexd/index/driver.py
- indexd/index/drivers/alchemy.py
- indexd/index/schema.py
- openapis/swagger.yaml
- tests/test_client.py
- tests/test_driver_alchemy_crud.py
- tests/test_setup.py
- add an optional file name column
- add migration function
> feat(file_name): add optional file name

- indexd/alias/drivers/alchemy.py
- indexd/index/drivers/alchemy.py
- indexd/utils.py
- tests/test_schema_migration.py
- tests/test_setup.py
Fix db migration for the case of brand new db
> fix(migration): Fix db migration

- README.md
- indexd/index/blueprint.py
- indexd/index/driver.py
- indexd/index/drivers/alchemy.py
- indexd/index/schema.py
- openapis/swagger.yaml
- tests/test_client.py
- tests/test_driver_alchemy_crud.py
- tests/test_schema_migration.py
- tests/test_setup.py
> feat(version_string): add optinal version string

- Dockerfile
patch Apache config to reference
X-Forwarded-For and X-UserId headers
setup by revproxy service
resolve #79
> fix(logging): real ip and user-id

- indexd/alias/schema.py
- indexd/index/schema.py
- tests/test_client.py
> fix(schema): allow multiple hashes

- README.md
- indexd/alias/schema.py
- indexd/index/blueprint.py
- indexd/index/schema.py
- openapis/swagger.yaml
- tests/test_client.py
Adds etag and crc hash types.
resolves #81
> feat(hashes): Support Etag and CRC hash types

- indexd/index/blueprint.py
- indexd/index/driver.py
- indexd/index/drivers/alchemy.py
- tests/test_client.py
Relates to https://github.com/uc-cdis/indexclient/pull/17
> feat(metadata): Allow querying by metadata.

- indexd/index/blueprint.py
- indexd/index/driver.py
- indexd/index/drivers/alchemy.py
- indexd/index/schema.py
- openapis/swagger.yaml
- tests/test_client.py
need to allow updating metadata
> feat(metadata): allow updating metadata

- Dockerfile
for https://github.com/uc-cdis/cloud-automation/issues/219
> feat(security): enable reqtimeout

- indexd/index/blueprint.py
> fix(add_version): check schema

- indexd/index/drivers/alchemy.py
- tests/test_client.py
resolve #89 
- support `/index/<did>`, `/index/<did>/latest` `/index/<did>/versions` supplied with baseid
- some style fixes
> feat(baseid): support get by baseid

- indexd/index/drivers/alchemy.py
> feat(latest): include baseid

- .travis.yml
- indexd/index/blueprint.py
- indexd/index/drivers/alchemy.py
- indexd/index/schema.py
- openapis/swagger.yaml
- tests/test_client.py
- tests/test_schema_migration.py
> feat(acl): add acl table

- indexd/index/blueprint.py
- indexd/index/driver.py
- indexd/index/drivers/alchemy.py
- openapis/swagger.yaml
- tests/test_client.py
> feat(latest_version): allow filter by has_version

- indexd/index/blueprint.py
- indexd/index/driver.py
- indexd/index/drivers/alchemy.py
- openapis/swagger.yaml
- tests/test_client.py
- support ids params
- return full records instead of ids so you don't need separate call to fetch the actual document
resolve #111
> feat(list-ids): support list with id params

- indexd/blueprint.py
- indexd/index/blueprint.py
- indexd/index/driver.py
- indexd/index/drivers/alchemy.py
- openapis/swagger.yaml
- tests/test_client.py
updates on /urls enpdoint
- support query by ids too
- return both url and metadata
- add swagger
> feat(urls): add metadata and swagger

- indexd/index/drivers/alchemy.py
- tests/test_client.py
also refactor the code to not do 2 lookups for baseid and did.
> chore(baseid): add index

- indexd/index/blueprint.py
- indexd/index/drivers/alchemy.py
- openapis/swagger.yaml
- tests/test_client.py
Couple of things that might need to change:
- use sqlalchemy contain method for url key
- pass urls_metadata:jsonString to GET url param
> urls_metadata partial match in list_with_params

- .gitignore
- indexd/app.py
- indexd/bulk/blueprint.py
- openapis/swagger.yaml
- setup.py
- tests/test_blueprint.py
- tests/test_client.py
Bulk get operations
```
POST /bulk/documents
["id1", "id2", ..., "idn"]'
```
Example
===
```shell
curl -XPOST --headers 'content-type: application/json' /bulk/documents --data '["id1", "id2", ..., "idn"]'
```
addresses https://github.com/uc-cdis/indexd/issues/141
> (PXD-988): bulk operation

- indexd/index/drivers/alchemy.py
An update may cause there to be a urls_metadata entry without
a urls entry depending on what gets updated first. This causes a schema
error. To avoid that, update each special field individually.
> fix(update): potentially out of order dicts

- indexd/index/drivers/alchemy.py
Update `SQLAlchemyIndexDriver.ids()` to use joinedload. This fixes the N+1 select issue in `GET /index`.
I tried testing various query parameters and got the same results before and after this change. I also saw a speedup (0.23 seconds vs. 1.20 seconds) when querying for a list of 100 IDs. Querying by URLs metadata didn't get much faster; for that case, I think we're limited by way we filter and/or the table structure.
> fix(TT-800): use joinedload in GET /index

- indexd/index/blueprint.py
- indexd/index/drivers/alchemy.py
- indexd/index/schema.py
- openapis/swagger.yaml
- tests/test_client.py
- tests/test_setup.py
Description about what this pull request does.
Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.
- Add `uploader` field to records
- Records should include an `uploader` field which indicates the user who uploaded/is uploading this file
- Support update (delete), query for `uploader` field in records
> PXD-2214 Feat/uploader field

- openapis/swagger.yaml
- tests/conftest.py
- tests/test_client.py
Update indexd Swagger docs to address PXD-2231 PXD-2233 PXD-2234 PXD-2235 PXD-2236 and fix other general discrepancies. Also refactor some parts of the yaml. 
- update swagger docs
> docs(swagger-updates): make various updates to docs, especially to models. PXD-2231 PXD-2233 PXD-2234 PXD-2235 PXD-2236 

- Dockerfile
- README.md
- deployment/apache-indexd.conf
Setup json log form in apache conf
> fix(apache.conf): setup json logs

- openapis/swagger.yaml
Fix Swagger doc BulkInputInfo model
> [PXP-2416] Fix BulkInputInfo model

- README.md
- indexd/index/blueprint.py
- indexd/index/drivers/alchemy.py
- indexd/index/schema.py
- openapis/swagger.yaml
- tests/test_setup.py
- Record now have a new `rbac` field
> feat(rbac): add rbac field and API

- test-requirements.txt
already using safe_load(), and in fact already on pyyaml 5.1. Just pinning............ 🤦‍♂
> [PXP-2658] Pin PyYAML 5.1

- README.md
- indexd/bulk/blueprint.py
- indexd/index/blueprint.py
- indexd/index/driver.py
- indexd/index/drivers/alchemy.py
- indexd/index/schema.py
- openapis/swagger.yaml
- tests/test_client.py
- tests/test_setup.py
- tests/util.py
- added new authz field (previously rbac field)
> feat(authz): rename rbac to authz and use list

- indexd/auth/__init__.py
- indexd/auth/driver.py
- indexd/auth/drivers/alchemy.py
- indexd/index/blueprint.py
- indexd/index/drivers/alchemy.py
- requirements.txt
- test-requirements.txt
- tests/conftest.py
- tests/test_driver_alchemy_crud.py
- Now Indexd calls Arborist for permission check
> protect API with Arborist

- .travis.yml
- setup.py
https://github.com/uc-cdis/indexd/commit/4666f58db2eca9973d8425bba618563c5424feb7
^ sqlalchemy and sqlalchemy-utils were bumped in requirements.txt but not in setup.py 🤦‍♂
> bump sqlalchemy and utils in setup

- Dockerfile
Description about what this pull request does
Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.
-
> chore(docker): use pybase-1.0.2

- bin/migrate_acl_authz.py
- Remove extra leading `/` in resource paths in migration
- Fix log message
- Make window size formatting string clearer
> fix(migration): bug fixes for authz migration

- bin/migrate_acl_authz.py
- Correct path for authz field in program/project case.
> fix(authz): swap program/project

- .travis.yml
- README.md
- test-requirements.txt
- Add coveralls integration for code coverage analytics
> chore(coveralls)

- setup.py
- add dependencies to setup.py that were missing (already exist in requirements.txt)
> chore(deps): add missing dependencies to setup.py

- .github/main.workflow
- .github/workflows/wool.yml
the old workflow format has been deprecated so wool is not running on PRs anymore
> update wool GH workflow

- indexd/auth/drivers/alchemy.py
- Improve messages in Authz errors
> Improve authz errors messages

- Dockerfile
- Fix an issue introduced in 2.0.0 that broke the "/_version" endpoint
> fix(version): fix COMMIT and VERSION data location

- openapis/swagger.yaml
Jira Ticket: [PXP-5778](https://ctds-planx.atlassian.net/browse/PXP-5778)
Added auth info to DRS endpoint swagger.
> (PXP-5778): Update swagger.yaml

- tests/test_drs.py
- Test to check encoded slash works on both drs and drs access endpoint.
> (PXP-5885): encoded-slash-test

- indexd/drs/blueprint.py
- openapis/swagger.yaml
- tests/test_drs.py
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- Remove presigned url from the `access_url` field in the drs object when authz is given.
> (feat) remove presigned_url from drs object

- indexd/auth/errors.py
- indexd/drs/blueprint.py
- indexd/errors.py
- indexd/fence_client.py
- tests/test_drs.py
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- The `object/<guid>/access/<access type>` endpoint throws a 500 instead of a 401 when the user is logged in but does not have access to the specific record.
- Added a general Fence Error handler when drs fails to catch error from fence
> (PXP-6233): fix error message handling for 401 error

- README.md
Inform user about postgresql prerequisite and provide instructions to be able to run setup.py
> Tell user about prerequisite

- .secrets.baseline
- indexd/index/blueprint.py
- openapis/swagger.yaml
- tests/default_test_settings.py
- tests/test_bundles.py
- tests/test_client.py
Jira Ticket: [PXP-7004](https://ctds-planx.atlassian.net/browse/PXP-7004)
Implemented dist endpoint and added unit test
> add _dist endpoint

- docs/drs.md
- indexd/auth/drivers/alchemy.py
- indexd/index/drivers/query/__init__.py
- indexd/index/drivers/query/urls.py
- indexd/urls/blueprint.py
- openapis/swagger.yaml
- Records with an empty `authz` can now be updated by admins
> Fix authz check for empty authz

- Dockerfile
- clear_prometheus_multiproc
- deployment/uwsgi/uwsgi.ini
Jira Ticket: [PXP-7422](https://ctds-planx.atlassian.net/browse/PXP-7422)
Adopting a new parent image to deliver improvement related to Nginx logging.
Also enabling the UWSGI status endpoint (to harvest metrics later).
- Inline Nginx access logs on stdout.
> task(observability): Enable UWSGI status endpoint and metrics for multiple workers

- .secrets.baseline
- indexd/auth/drivers/alchemy.py
- tests/conftest.py
- tests/test_client.py
Jira Ticket: [PXP-8132](https://ctds-planx.atlassian.net/browse/PXP-8132)
- Indexd admins can perform any operation
- Add unit tests fixture to mock calls to Arborist easily
> PXP-8132 Add indexd admin logic

- README.md
- docs/local_dev_environment.md
* Add notes for local development
> Add local development notes

- Dockerfile
Jira Ticket: [PXP-8930](https://ctds-planx.atlassian.net/browse/PXP-8930)
https://stackoverflow.com/questions/59895745/poetry-fails-to-install-in-docker
- Use new Python base image (now: Debian, before: Alpine)
> Update expired image cert

- .travis.yml
- Dockerfile
- poetry.lock
- pyproject.toml
Jira Ticket: [PXP-9634](https://ctds-planx.atlassian.net/browse/PXP-9634)
* Upgrade to python3.9
> PXP-9634 feat(python3.9): upgrade to python3.9

- .github/workflows/image_build_push.yaml
Jira Ticket: [PXP-9634](https://ctds-planx.atlassian.net/browse/PXP-9634)
* use central workflow github actions for image build and push
> PXP-9634 feat(update-build): use github actions for build and push

- .gitignore
- indexd/drs/blueprint.py
- indexd/index/blueprint.py
- indexd/index/drivers/alchemy.py
- indexd/index/schema.py
- openapis/swagger.yaml
- pyproject.toml
- tests/test_drs.py
- tests/test_setup.py
Jira Ticket: [PXP-6421](https://ctds-planx.atlassian.net/browse/PXP-6421)
- Adds description field when creating/updating records.
- Maps indexd description to drs description for drs endpoints.
- indexclient changed to pre-release branch temporarily to satisfy tests the require the addition of description to indexclient.
[PXP-6421]: https://ctds-planx.atlassian.net/browse/PXP-6421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(PXP-6421): DRS description and version support added

- .secrets.baseline
- indexd/index/schema.py
- pyproject.toml
- tests/test_client.py
Jira Ticket: [PXP-6421](https://ctds-planx.atlassian.net/browse/PXP-6421)
- Fixes issue where updates to a record's description were not reflected.
[PXP-6421]: https://ctds-planx.atlassian.net/browse/PXP-6421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bug(PXP-6421): Fixes description not updating for records.

- indexd/index/blueprint.py
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- Fix the routing to the alias endpoint (This fixes data submission in helm)
> Fix alias endpoint for helm

- pyproject.toml
Jira Ticket: [DCF-1384](https://ctds-planx.atlassian.net/browse/DCF-1384)
- flask = "^2.3.3"
[DCF-1384]: https://ctds-planx.atlassian.net/browse/DCF-1384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCF-1384: Update flask

- poetry.lock
- pyproject.toml
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/PPS-2007 and https://ctds-planx.atlassian.net/browse/PPS-2012
Unblock dependency update in Sheepdog (https://github.com/uc-cdis/sheepdog/pull/450)
- `authutils` to version 7.0.0
> PPS-2007 PPS-2012 authutils to 7.0.0
